### PR TITLE
Added myself as the organiser for Bangalore, India

### PR DESCRIPTION
**Pull request by rajivpriyadarshi**
Hey. I am a huge Yes theory fan since when the channel was started. I would love to initiate the culture here in India.
Thanks

### CODE REVIEW

**Comment by noel-schenk** [comment]
hey mate thank you for the request ... this page was for germany only but I added india as the second country. It's a bit different now but I added you :smile: thank you!

**Comment by rajivpriyadarshi** [comment]
> hey mate thank you for the request ... this page was for germany only but I added india as the second country. It's a bit different now but I added you 😄 thank you!

Thanks, Noel. I am a UX/UI designer.  I will help design this page, as well.

**Comment by rajivpriyadarshi** [comment]
Hey Noel. Turns out there is already a YesFam group in Bangalore. There are few other groups from India.
Can you mark in as the representative for India, and remove me from Bangalore. 
I'd help those multiple groups collaborate with each other, and organize pan India meetups.

**Comment by noel-schenk** [comment]
Hey mate I don't know the indian yes theory organization too well. I think you are in the OC India WhatsApp group. please discuss it in there, thats exactly what it is perfect about. There are other people who have organized meetups.

**Pull request closed without merging**
