### PR TITLE
Improved wording, fixed typos and refactored formatting for better readability

### PR DESCRIPTION
**Pull request by marco-krammer**

### CODE REVIEW

**Comment by marco-krammer** [comment]
@noelelias also just noticed that the repository topic is not up to date as it isn't Germany only anymore

**Review by noel-schenk — CHANGES_REQUESTED** [review]
Hey @marco-krammer thank you so much for the fixes. There is some stuff, that has to be changed but else it looks good!

Titles like Groupchats have to either be changed in all files (india,gernaby,gb) at every position or not at all (we are working on automating stuff so consistency is really important. If you make a space in the titles the link for example (#groupchat) will be (#group-chat) and has to be changed in every file.

Also there are some rules for the lists, because of how it gets formated:
* the last item has to end with 2 spaces
* after the last item there has to be a new line before new text or a title  

If you want to create a new line add 2 spaces to the new line otherwise it's not recognized

**Comment by marco-krammer** [comment]
@noelelias completely forgot about link handling in Markdown for GH Pages ;) Will add your proposed changes later.

**Comment by marco-krammer** [comment]
@noelelias please check if I didn't miss anything :)
Also all rules that need to be considered (e.g. two spaces after last list item) when contributing should be documented in a contributing.md (or similar) imho.

**Comment by noel-schenk** [comment]
hey mate thank you for the update. I will look into it. But we are working on a new version rn. I will probably merge it directly into that.

**Comment by noel-schenk** [comment]
Sorry I couldn't solve the conflict but @ you in the changes

**Pull request closed without merging**
